
CREATE OR REPLACE VIEW  FINANCE_VIEW AS
	SELECT 
		VEHICLES.REG_ID, 
		VEHICLES.MILEAGE,
		VEHICLES.MODEL,
		VEHICLES.CURRENT_VALUE,
		TYPES_OF_VEHICLES.TYPE_DEDESCRIPTION AS VEHICLE_CLASS, 
		VEHICLES.REPLACEMENT_VALUE, 
		VEHICLES.STATUS,
		TYPES_OF_VEHICLES.SPECIAL_QUALIFICATION AS REQUIRED_SPECIAL_QUALIFICATION, 
		COUNT(SERVICES.SERVICE_ID)  AS NUMBER_OF_SERVICES,
		SUM(REPAIR_COSTS.VALUE) AS TOTAL_SPENT_IN_REPAIRS
		
	FROM VEHICLES
		INNER JOIN TYPES_OF_VEHICLES ON TYPES_OF_VEHICLES.TYPE_OF_VEHICLE_ID = VEHICLES.TYPE_OF_VEHICLE_ID
		INNER JOIN SERVICE ON VEHICLES.REG_ID = SERVICE.REG_ID
		INNER JOIN INSURANCE_CLAIMS ON VEHICLES.REG_ID = INSURANCE_CLAIMS.REG_ID
		INNER JOIN REPAIR_COSTS ON INSURANCE_CLAIMS.INSURANCE_CLAME_ID = REPAIR_COSTS.INSURANCE_CLAME_ID
		
	WHERE
		TYPES_OF_VEHICLES.DESCRIPTION IN ('Car', 'Light rigid heavy vehicle', 'Medium rigid heavy vehicle', 'Heavy rigid vehicle', 'Tractor') AND
		TO_CHAR(VEH.BOUGHT_DATE, 'YYYY') <= (TO_CHAR(SYSDATE, 'YYYY') - 2)
	
	GROUP BY
		VEHICLES.REG_ID, 
		VEHICLES.MILEAGE,
		VEHICLES.MODEL,
		VEHICLES.CURRENT_VALUE,
		TYPES_OF_VEHICLES.TYPE_DEDESCRIPTION, 
		VEHICLES.REPLACEMENT_VALUE, 
		VEHICLES.STATUS,
		TYPES_OF_VEHICLES.SPECIAL_QUALIFICATION 
	ORDER BY VEH.MILEAGE DESC;

GRANT SELECT ON FINANCE_VIEW TO FINANCE_PROFILE;