-- Se realiza recreación de Objetos del taller # 1 (Assingment #1)
-- Se anexan los scripts

-- CREACIÓN DE TABLESPACES

CREATE TABLESPACE UNDOTBS2 DATAFILE 'D:\ORACLE\DATA\UNDOTBS2_DAT01.DBF' SIZE 5 M;
CREATE UNDO TABLESPACE UNDOTBS2  DATAFILE 'D:\ORACLE\DATA\UNDOTBS2_DAT01.DBF' SIZE 5 M;
ALTER SYSTEM SET UNDO_TABLESPACE =UNDOTBS2 SCOPE =MEMORY;

-- CREACION DE USUARIOS Y ROLES

CREATE USER ELDI IDENTIFIED BY "VANEGAS01" DEFAULT TABLESPACE VEHICLES_FLEET TEMPORARY TABLESPACE TEMP;
GRANT UNLIMITED TABLESPACE TO ELDI;
CREATE PROFILE "MANAGER_PROFILE" LIMIT
CPU_PER_SESSION DEFAULT
CPU_PER_CALL DEFAULT
CONNECT_TIME DEFAULT
IDLE_TIME 15
SESSIONS_PER_USER 1
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL DEFAULT
PRIVATE_SGA DEFAULT
COMPOSITE_LIMIT DEFAULT
PASSWORD_LIFE_TIME 40
PASSWORD_GRACE_TIME DEFAULT
PASSWORD_REUSE_MAX DEFAULT
PASSWORD_REUSE_TIME DEFAULT
PASSWORD_VERIFY_FUNCTION DEFAULT
FAILED_LOGIN_ATTEMPTS 4
PASSWORD_LOCK_TIME DEFAULT;

CREATE PROFILE "FINANCE_PROFILE" LIMIT
CPU_PER_SESSION DEFAULT
CPU_PER_CALL DEFAULT
CONNECT_TIME DEFAULT
IDLE_TIME 5
SESSIONS_PER_USER 1
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL DEFAULT
PRIVATE_SGA DEFAULT
COMPOSITE_LIMIT DEFAULT
PASSWORD_LIFE_TIME 15
PASSWORD_GRACE_TIME DEFAULT
PASSWORD_REUSE_MAX DEFAULT
PASSWORD_REUSE_TIME DEFAULT
PASSWORD_VERIFY_FUNCTION DEFAULT
FAILED_LOGIN_ATTEMPTS 2
PASSWORD_LOCK_TIME DEFAULT;


CREATE ROLE WITHOUT_PRIVILEGES;
GRANT ALL PRIVILEGES TO WITHOUT_PRIVILEGES;
REVOKE ALL PRIVILEGES FROM WITHOUT_PRIVILEGES;

CREATE USER CRISTIAN IDENTIFIED BY "CRISTIAN01" DEFAULT TABLESPACE VEHICLES_FLEET TEMPORARY TABLESPACE TEMP PROFILE MANAGER_PROFILE;
CREATE USER DENIS IDENTIFIED BY "DENIS01" DEFAULT TABLESPACE VEHICLES_FLEET TEMPORARY TABLESPACE TEMP PROFILE FINANCE_PROFILE;

CREATE PROFILE "SERVICE_PROFILE" LIMIT
CPU_PER_SESSION DEFAULT
CPU_PER_CALL DEFAULT
CONNECT_TIME DEFAULT
IDLE_TIME 10
SESSIONS_PER_USER 2
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL DEFAULT
PRIVATE_SGA DEFAULT
COMPOSITE_LIMIT DEFAULT
PASSWORD_LIFE_TIME 20
PASSWORD_GRACE_TIME DEFAULT
PASSWORD_REUSE_MAX DEFAULT
PASSWORD_REUSE_TIME DEFAULT
PASSWORD_VERIFY_FUNCTION DEFAULT
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME DEFAULT;

CREATE PROFILE "DEVELOPMENT" LIMIT
CPU_PER_SESSION DEFAULT
CPU_PER_CALL DEFAULT
CONNECT_TIME DEFAULT
IDLE_TIME 30
SESSIONS_PER_USER 2
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL DEFAULT
PRIVATE_SGA DEFAULT
COMPOSITE_LIMIT DEFAULT
PASSWORD_LIFE_TIME 100
PASSWORD_GRACE_TIME DEFAULT
PASSWORD_REUSE_MAX DEFAULT
PASSWORD_REUSE_TIME DEFAULT
PASSWORD_VERIFY_FUNCTION DEFAULT
FAILED_LOGIN_ATTEMPTS 1
PASSWORD_LOCK_TIME DEFAULT;

CREATE USER ANDRES IDENTIFIED BY "ANDRES01" DEFAULT TABLESPACE VEHICLES_FLEET TEMPORARY TABLESPACE TEMP PROFILE SERVICE_PROFILE;
CREATE USER ELDIFONSO IDENTIFIED BY "ELDIFONSO01" DEFAULT TABLESPACE VEHICLES_FLEET TEMPORARY TABLESPACE TEMP PROFILE DEVELOPMENT;
GRANT CREATE SESSION TO CRISTIAN;
GRANT CREATE SESSION TO DENIS;
GRANT CREATE SESSION TO ANDRES;
GRANT CREATE SESSION TO ELDIFONSO;
GRANT WITHOUT_PRIVILEGES TO CRISTIAN;
GRANT WITHOUT_PRIVILEGES TO DENIS;
GRANT WITHOUT_PRIVILEGES TO ANDRES;
ALTER USER CRISTIAN ACCOUNT LOCK;
ALTER USER DENIS ACCOUNT LOCK;
ALTER USER ANDRES ACCOUNT LOCK;


-- Adecuaciones necesarias del ambiente para creación de objetos
-- Dueño de los objetos usuario ELDI

GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "ELDI" ;
GRANT "SELECT_CATALOG_ROLE" TO "ELDI" ;
GRANT "CONNECT" TO "ELDI" ;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "ELDI" ;
GRANT "SCHEDULER_ADMIN" TO "ELDI" ;
GRANT "RECOVERY_CATALOG_OWNER" TO "ELDI" ;
GRANT "RESOURCE" TO "ELDI" ;


-----------------------------------------------------------------------------------------------------------------------------------------
-- CREACION DE TABLAS, SECUENCIAS 
-----------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
--  DDL for Table DRIVER_QUALIFICATION
--------------------------------------------------------

  CREATE TABLE "ELDI"."DRIVER_QUALIFICATION" 
   (	"QUIALIFICATION_ID" NUMBER(12,0), 
		"QUALIFICATION_DESC" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Table DRIVERS
--------------------------------------------------------

  CREATE TABLE "ELDI"."DRIVERS" 
   (	"EMPLOYEE_ID" NUMBER(12,0),
		"EMPLOYEE_COD" VARCHAR2(20 BYTE),
		"EMPLOYEE_NAME" VARCHAR2(100 BYTE), 
		"INIT_DATE" DATE, 
		"STATUS" VARCHAR2(10 BYTE), 
		"QUIALIFICATION_ID" NUMBER(12,0), 
		"QUALIFICATION_STATUS" VARCHAR2(12 BYTE), 
		"QUALIFICATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Table INSURANCE_CLAIMS
--------------------------------------------------------

  CREATE TABLE "ELDI"."INSURANCE_CLAIMS" 
   (	"INSURANCE_CLAIM_ID" NUMBER(12,0), 
		"REG_ID" NUMBER(12,0), 
		"POLICY_NUMBER" VARCHAR2(30 BYTE), 
		"LOSS_DATE" DATE, 
		"ISSUE_DATE" DATE, 
		"NATURE_OF_DAMAGE" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Table REPAIR_COSTS
--------------------------------------------------------

  CREATE TABLE "ELDI"."REPAIR_COSTS" 
   (	"REPAIR_ID" NUMBER(12,0), 
		"REPAIR_DATE" DATE, 
		"INSURANCE_CLAME_ID" NUMBER(12,0), 
		"REPAIR_DESC" CLOB, 
		"VALUE" NUMBER(12,0), 
		"STATUS" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" 
 LOB ("REPAIR_DESC") STORE AS BASICFILE (
  TABLESPACE "VEHICLES_FLEET" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SERVICE
--------------------------------------------------------

  CREATE TABLE "ELDI"."SERVICES" 
   (	"SERVICE_ID" NUMBER(12,0), 
		"REG_ID" NUMBER(12,0), 
		"ISSUE_DATE" DATE,
		"NUMBER_SERVICE" NUMBER(12,0),
		"DESCRIPTION" VARCHAR2(500 BYTE),
		"SERVICE_STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Table SERVICES_DETAIL
--------------------------------------------------------

  CREATE TABLE "ELDI"."SERVICES_DETAIL" 
   (	"SERVICE_TYPE_ID" NUMBER(12,0), 
		"SERVICE_ID" NUMBER(12,0),
		"SERVICE_DETAIL_STATUS" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Table TYPE_OF_VEHICLES
--------------------------------------------------------

  CREATE TABLE "ELDI"."TYPE_OF_VEHICLES" 
   (	"TYPE_ID" NUMBER(12,0), 
		"TYPE_DESCRIPTION" VARCHAR2(30 BYTE), 
		"SPECIAL_QUALIFICATION" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Table TYPE_SERVICES
--------------------------------------------------------

  CREATE TABLE "ELDI"."TYPE_SERVICES" 
   (	"SERVICE_TYPE_ID" NUMBER(12,0), 
		"SERVICE_NAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Table VEH_DRIVER_AUTHO
--------------------------------------------------------

  CREATE TABLE "ELDI"."VEH_DRIVER_AUTHO" 
   (	"REG_ID" NUMBER(12,0),
		"EMPLOYEE_ID" NUMBER(12,0),   
		"AUTHORIZED" VARCHAR2(1 BYTE), 
		"STATUS_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Table VEHICLES
--------------------------------------------------------

  CREATE TABLE "ELDI"."VEHICLES" 
   (	"REG_ID" NUMBER, 
	"PLATE" VARCHAR2(6 BYTE), 
	"STATUS" VARCHAR2(9 BYTE), 
	"MILEAGE" NUMBER(6,0), 
	"MODEL" NUMBER(5,0), 
	"TYPE_ID" NUMBER(12,0), 
	"PURCHASE_DATE" DATE, 
	"CURRENT_VALUE" NUMBER(16,0), 
	"REPLACEMENT_VALUE" NUMBER(16,0), 
	"TAXED_VALUE" NUMBER(16,0), 
	"TAXED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;

---------------------------------------------------------------------------------------------------------------------------------------------
-- CREACION DE SECUENCIAS 
---------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------
--  DDL for Sequence SEQ_DRIVERS
--------------------------------------------------------

   CREATE SEQUENCE  "ELDI"."SEQ_DRIVERS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_INSUR_CLAIMS
--------------------------------------------------------

   CREATE SEQUENCE  "ELDI"."SEQ_INSUR_CLAIMS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QUIALIFICATION
--------------------------------------------------------

   CREATE SEQUENCE  "ELDI"."SEQ_QUIALIFICATION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REPAIR_COSTS
--------------------------------------------------------

   CREATE SEQUENCE  "ELDI"."SEQ_REPAIR_COSTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SERVICE
--------------------------------------------------------

   CREATE SEQUENCE  "ELDI"."SEQ_SERVICES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TYPE_OF_VEHIC
--------------------------------------------------------

   CREATE SEQUENCE  "ELDI"."SEQ_TYPE_OF_VEHIC"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TYPE_SERV
--------------------------------------------------------

   CREATE SEQUENCE  "ELDI"."SEQ_TYPE_SERV"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_VEHICLES
--------------------------------------------------------

   CREATE SEQUENCE  "ELDI"."SEQ_VEHICLES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
   
--------------------------------------------------------
--  CREACION DE INDICES
--------------------------------------------------------
   

--------------------------------------------------------
--  DDL for Index REPAIR_COSTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELDI"."REPAIR_COSTS_PK" ON "ELDI"."REPAIR_COSTS" ("REPAIR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
  
--------------------------------------------------------
--  DDL for Index VEHICLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELDI"."VEHICLES_PK" ON "ELDI"."VEHICLES" ("REG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
  
  CREATE UNIQUE INDEX "ELDI"."IDX_VEHICLES_PLATE" ON "ELDI"."VEHICLES" ("PLATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Index DRIVER_QUALIFICATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELDI"."DRIVER_QUALIFICATION_PK" ON "ELDI"."DRIVER_QUALIFICATION" ("QUIALIFICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Index SERVICES_DETAIL_PK
--------------------------------------------------------

  /*CREATE UNIQUE INDEX "ELDI"."SERVICES_DETAIL_PK" ON "ELDI"."SERVICES_DETAIL" ("SERVICE_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;*/
--------------------------------------------------------
--  DDL for Index VEH_DRIVER_AUTHO_PK
--------------------------------------------------------

  /*CREATE UNIQUE INDEX "ELDI"."VEH_DRIVER_AUTHO_PK" ON "ELDI"."VEH_DRIVER_AUTHO" ("REG_ID_EMPLOEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;*/
--------------------------------------------------------
--  DDL for Index SERVICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELDI"."SERVICES_PK" ON "ELDI"."SERVICES" ("SERVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Index DRIVERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELDI"."DRIVERS_PK" ON "ELDI"."DRIVERS" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
  
  CREATE UNIQUE INDEX "ELDI"."IDX_DRIVERS_COD" ON "ELDI"."DRIVERS" ("EMPLOYEE_COD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Index TYPE_SERVICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELDI"."TYPE_SERVICES_PK" ON "ELDI"."TYPE_SERVICES" ("SERVICE_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Index TYPE_OF_VEHICLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELDI"."TYPE_OF_VEHICLES_PK" ON "ELDI"."TYPE_OF_VEHICLES" ("TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Index INSURANCE_CLAIMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELDI"."INSURANCE_CLAIMS_PK" ON "ELDI"."INSURANCE_CLAIMS" ("INSURANCE_CLAIM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
  
----------------------------------------------------------------------------------------------------------------
--  CREACION DE CONSTRAINTS 
----------------------------------------------------------------------------------------------------------------
  
 
--------------------------------------------------------
--  Constraints for Table TYPE_OF_VEHICLES
--------------------------------------------------------

  ALTER TABLE "ELDI"."TYPE_OF_VEHICLES" ADD CONSTRAINT "TYPE_OF_VEHICLES_PK" PRIMARY KEY ("TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET"  ENABLE;
  
  ALTER TABLE "ELDI"."TYPE_OF_VEHICLES" MODIFY ("SPECIAL_QUALIFICATION" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."TYPE_OF_VEHICLES" MODIFY ("TYPE_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."TYPE_OF_VEHICLES" MODIFY ("TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPAIR_COSTS
--------------------------------------------------------

  ALTER TABLE "ELDI"."REPAIR_COSTS" ADD CONSTRAINT "REPAIR_COSTS_PK" PRIMARY KEY ("REPAIR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET"  ENABLE;
  ALTER TABLE "ELDI"."REPAIR_COSTS" MODIFY ("INSURANCE_CLAME_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."REPAIR_COSTS" MODIFY ("REPAIR_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."REPAIR_COSTS" MODIFY ("REPAIR_DATE" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."REPAIR_COSTS" MODIFY ("REPAIR_DESC" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."REPAIR_COSTS" MODIFY ("VALUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEH_DRIVER_AUTHO
--------------------------------------------------------

  ALTER TABLE "ELDI"."VEH_DRIVER_AUTHO" MODIFY ("REG_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEH_DRIVER_AUTHO" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEH_DRIVER_AUTHO" MODIFY ("AUTHORIZED" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEH_DRIVER_AUTHO" MODIFY ("STATUS_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DRIVERS
--------------------------------------------------------

  ALTER TABLE "ELDI"."DRIVERS" ADD CONSTRAINT "DRIVERS_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET"  ENABLE;
  ALTER TABLE "ELDI"."DRIVERS" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."DRIVERS" MODIFY ("EMPLOYEE_COD" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."DRIVERS" MODIFY ("EMPLOYEE_NAME" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."DRIVERS" MODIFY ("INIT_DATE" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."DRIVERS" MODIFY ("QUIALIFICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."DRIVERS" MODIFY ("QUALIFICATION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."DRIVERS" MODIFY ("QUALIFICATION_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICES_DETAIL
--------------------------------------------------------

  ALTER TABLE "ELDI"."SERVICES_DETAIL" ADD CONSTRAINT "SERVICES_DETAIL_PK" PRIMARY KEY ("SERVICE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET"  ENABLE;
  ALTER TABLE "ELDI"."SERVICES_DETAIL" MODIFY ("SERVICE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."SERVICES_DETAIL" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."SERVICES_DETAIL" MODIFY ("SERVICE_DETAIL_STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE
--------------------------------------------------------

  ALTER TABLE "ELDI"."SERVICES" ADD CONSTRAINT "SERVICES_PK" PRIMARY KEY ("SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET"  ENABLE;
  ALTER TABLE "ELDI"."SERVICE" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."SERVICE" MODIFY ("REG_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."SERVICE" MODIFY ("ISSUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."SERVICE" MODIFY ("NUMBER_SERVICE" NOT NULL ENABLE);
  
  
--------------------------------------------------------
--  Constraints for Table DRIVER_QUALIFICATION
--------------------------------------------------------

  ALTER TABLE "ELDI"."DRIVER_QUALIFICATION" ADD CONSTRAINT "DRIVER_QUALIFICATION_PK" PRIMARY KEY ("QUIALIFICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET"  ENABLE;
  ALTER TABLE "ELDI"."DRIVER_QUALIFICATION" MODIFY ("QUIALIFICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."DRIVER_QUALIFICATION" MODIFY ("QUALIFICATION_DESC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INSURANCE_CLAIMS
--------------------------------------------------------

  ALTER TABLE "ELDI"."INSURANCE_CLAIMS" ADD CONSTRAINT "INSURANCE_CLAIMS_PK" PRIMARY KEY ("INSURANCE_CLAIM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET"  ENABLE;
  ALTER TABLE "ELDI"."INSURANCE_CLAIMS" MODIFY ("REG_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."INSURANCE_CLAIMS" MODIFY ("INSURANCE_CLAIM_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."INSURANCE_CLAIMS" MODIFY ("POLICY_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."INSURANCE_CLAIMS" MODIFY ("LOSS_DATE" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."INSURANCE_CLAIMS" MODIFY ("ISSUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."INSURANCE_CLAIMS" MODIFY ("NATURE_OF_DAMAGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEHICLES
--------------------------------------------------------

  ALTER TABLE "ELDI"."VEHICLES" ADD CONSTRAINT "VEHICLES_PK" PRIMARY KEY ("REG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET"  ENABLE;
  ALTER TABLE "ELDI"."VEHICLES" MODIFY ("REG_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEHICLES" MODIFY ("PLATE" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEHICLES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEHICLES" MODIFY ("MILEAGE" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEHICLES" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEHICLES" MODIFY ("TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEHICLES" MODIFY ("PURCHASE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEHICLES" MODIFY ("CURRENT_VALUE" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEHICLES" MODIFY ("REPLACEMENT_VALUE" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEHICLES" MODIFY ("TAXED_VALUE" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEHICLES" MODIFY ("TAXED_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPE_SERVICES
--------------------------------------------------------

  ALTER TABLE "ELDI"."TYPE_SERVICES" ADD CONSTRAINT "TYPE_SERVICES_PK" PRIMARY KEY ("SERVICE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET"  ENABLE;
  
  ALTER TABLE "ELDI"."TYPE_SERVICES" MODIFY ("SERVICE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."TYPE_SERVICES" MODIFY ("SERVICE_NAME" NOT NULL ENABLE);
  
  
-----------------------------------------------------------------------------------------------------------------  
 --  AJUSTES A LA CREACIÓN INICIAL DEL MODELO
 -----------------------------------------------------------------------------------------------------------------  
 -- RECREACION DE TABLA
/*DROP TABLE "ELDI"."VEH_DRIVER_AUTHO";
 --------------------------------------------------------
--  DDL for Table VEH_DRIVER_AUTHO
--------------------------------------------------------

  CREATE TABLE "ELDI"."VEH_DRIVER_AUTHO" 
   (	"REG_ID" NUMBER(12,0), 
	"EMPLOYEE_ID" NUMBER(12,0), 
	"AUTHORIZED" VARCHAR2(1 BYTE), 
	"STATUS_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  DDL for Index VEH_DRIVER_AUTHO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELDI"."VEH_DRIVER_AUTHO_PK" ON "ELDI"."VEH_DRIVER_AUTHO" ("REG_ID", "EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET" ;
--------------------------------------------------------
--  Constraints for Table VEH_DRIVER_AUTHO
--------------------------------------------------------

  ALTER TABLE "ELDI"."VEH_DRIVER_AUTHO" ADD CONSTRAINT "VEH_DRIVER_AUTHO_PK" PRIMARY KEY ("REG_ID", "EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEHICLES_FLEET"  ENABLE;
  ALTER TABLE "ELDI"."VEH_DRIVER_AUTHO" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "ELDI"."VEH_DRIVER_AUTHO" MODIFY ("REG_ID" NOT NULL ENABLE);*/

  
  -------------------------------------------------------------------------------------------------------------------------------------
  ---  CREACIÓN DE CONSTRAINTS DE LLAVE FORANEA Y DE CHEQUEO
  -------------------------------------------------------------------------------------------------------------------------------------

ALTER TABLE "ELDI"."VEHICLES" ADD CONSTRAINT VEHICLES_FK1 FOREIGN KEY("TYPE_ID") REFERENCES "TYPE_OF_VEHICLES"("TYPE_ID");
ALTER TABLE "ELDI"."DRIVERS" ADD CONSTRAINT DRIVERS_FK1 FOREIGN KEY("QUIALIFICATION_ID") REFERENCES "DRIVER_QUALIFICATION"("QUIALIFICATION_ID");
ALTER TABLE "ELDI"."INSURANCE_CLAIMS" ADD CONSTRAINT INSURANCE_CLAIMS_FK FOREIGN KEY("REG_ID") REFERENCES "VEHICLES"("REG_ID");
ALTER TABLE "ELDI"."REPAIR_COSTS" ADD CONSTRAINT REPAIR_COSTS_FK1 FOREIGN KEY("INSURANCE_CLAME_ID") REFERENCES "INSURANCE_CLAIMS"("INSURANCE_CLAIM_ID");
ALTER TABLE "ELDI"."SERVICES_DETAIL" ADD CONSTRAINT SERVICE_DETAIL_FK1 FOREIGN KEY("SERVICE_ID") REFERENCES "SERVICE"("SERVICE_ID");
ALTER TABLE "ELDI"."SERVICES_DETAIL" ADD CONSTRAINT SERVICE_DETAIL_FK FOREIGN KEY("SERVICE_TYPE_ID") REFERENCES "TYPE_SERVICES"("SERVICE_TYPE_ID");
/*ALTER TABLE "ELDI"."TYPE_OF_VEHICLES" ADD CONSTRAINT TYPE_OF_VEHICLES_FK1 FOREIGN KEY("QUALIFICATION_ID") REFERENCES "DRIVER_QUALIFICATION"("QUIALIFICATION_ID");*/
ALTER TABLE "ELDI"."SERVICES" ADD CONSTRAINT SERVICE_FK1 FOREIGN KEY("REG_ID") REFERENCES "VEHICLES"("REG_ID");
--ALTER TABLE "ELDI"."REPAIR_COSTS" ADD CONSTRAINT REPAIR_COSTS_FK2 FOREIGN KEY("REG_ID") REFERENCES "VEHICLES"("REG_ID");
ALTER TABLE "ELDI"."VEH_DRIVER_AUTHO" ADD CONSTRAINT VEH_DRIVER_AUTHO_FK1 FOREIGN KEY("EMPLOYEE_ID") REFERENCES "DRIVERS"("EMPLOYEE_ID");
ALTER TABLE "ELDI"."VEH_DRIVER_AUTHO" ADD CONSTRAINT VEH_DRIVER_AUTHO_FK2 FOREIGN KEY("REG_ID") REFERENCES "VEHICLES"("REG_ID");

ALTER TABLE VEHICLES ADD (CONSTRAINT ck_vehstatus_01 
  CHECK (UPPER(STATUS)='ACTIVE' OR 
         UPPER(STATUS)='INACTIVE' OR
         UPPER(STATUS)='REPAIRING' OR
         UPPER(STATUS)='SOLD')
 );


ALTER TABLE DRIVERS ADD (CONSTRAINT ck_quastatus_01 
  CHECK (UPPER(QUALIFICATION_STATUS)='ACTIVE' OR 
         UPPER(QUALIFICATION_STATUS)='DISQUALIFIED' OR
         UPPER(QUALIFICATION_STATUS)='EXPIRED' OR
         UPPER(QUALIFICATION_STATUS)='INACTIVE')
 );

ALTER TABLE REPAIR_COSTS ADD (CONSTRAINT ck_repstatus_01 
  CHECK (UPPER(STATUS)='PENDING' OR 
         UPPER(STATUS)='PAID' )
 );


ALTER TABLE SERVICES ADD (CONSTRAINT ck_serstatus_01 
  CHECK (UPPER(SERVICE_STATUS)='OK' OR 
         UPPER(SERVICE_STATUS)='PENDING' OR
         UPPER(SERVICE_STATUS)='SCHEDULED,')
 );
 
 ALTER TABLE SERVICES_DETAIL ADD (CONSTRAINT ck_serdetstatus_01 
  CHECK (UPPER(SERVICE_DETAIL_STATUS)='OK' OR 
         UPPER(SERVICE_DETAIL_STATUS)='PENDING' OR
         UPPER(SERVICE_DETAIL_STATUS)='NEEDS_REPAIR,' OR
		 UPPER(SERVICE_DETAIL_STATUS)='OBSERVATIONS')
 );


-------------------------------------------------------------------------------------------------------------------------------------------------------
---    CREACION DE TRIGGERS DE SECUENCIAS DE BASE DE DATOS
-------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_TYPE_SERVICES 
BEFORE INSERT ON TYPE_SERVICES FOR EACH ROW
WHEN (new."SERVICE_TYPE_ID" IS NULL) 
BEGIN
  SELECT SEQ_TYPE_SERV.NEXTVAL 
  INTO :new."SERVICE_TYPE_ID" 
  FROM dual;
END;

 CREATE OR REPLACE TRIGGER TRG_DRIVER_QUALIFICATION  
BEFORE INSERT ON DRIVER_QUALIFICATION FOR EACH ROW
WHEN (new."QUIALIFICATION_ID" IS NULL) 
BEGIN
  SELECT SEQ_QUIALIFICATION.NEXTVAL 
  INTO :new."QUIALIFICATION_ID" 
  FROM dual;
END;

 CREATE OR REPLACE TRIGGER TRG_DRIVERS  
BEFORE INSERT ON DRIVERS FOR EACH ROW
WHEN (new."EMPLOYEE_ID" IS NULL) 
BEGIN
  SELECT SEQ_DRIVERS.NEXTVAL 
  INTO :new."EMPLOYEE_ID" 
  FROM dual;
END;

 CREATE OR REPLACE TRIGGER TRG_TYPE_OF_VEHICLES
BEFORE INSERT ON TYPE_OF_VEHICLES FOR EACH ROW
WHEN (new."TYPE_ID" IS NULL) 
BEGIN
  SELECT SEQ_TYPE_OF_VEHIC.NEXTVAL 
  INTO :new."TYPE_ID" 
  FROM dual;
END;

 CREATE OR REPLACE TRIGGER TRG_VEHICLES
BEFORE INSERT ON VEHICLES FOR EACH ROW
WHEN (new."REG_ID" IS NULL) 
BEGIN
  SELECT SEQ_VEHICLES.NEXTVAL 
  INTO :new."REG_ID" 
  FROM dual;
END;

 CREATE OR REPLACE TRIGGER TRG_INSURANCE_CLAIM
BEFORE INSERT ON INSURANCE_CLAIMS FOR EACH ROW
WHEN (new."INSURANCE_CLAIM_ID" IS NULL) 
BEGIN
  SELECT SEQ_INSUR_CLAIMS.NEXTVAL 
  INTO :new."INSURANCE_CLAIM_ID" 
  FROM dual;
END;

 CREATE OR REPLACE TRIGGER TRG_SERVICE
BEFORE INSERT ON SERVICES FOR EACH ROW
WHEN (new."SERVICE_ID" IS NULL) 
BEGIN
  SELECT SEQ_SERVICE.NEXTVAL 
  INTO :new."SERVICE_ID" 
  FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_REPAIR_COSTS
BEFORE INSERT ON REPAIR_COSTS FOR EACH ROW
WHEN (new."REPAIR_ID" IS NULL) 
BEGIN
  SELECT SEQ_REPAIR_COSTS.NEXTVAL 
  INTO :new."REPAIR_ID" 
  FROM dual;
END;



---------------------------------------------------------------------------------------------------------------------------------------------
--  CARGA DE DATOS EN TABLAS
---------------------------------------------------------------------------------------------------------------------------------------------
-- TYPE_SERVICES

INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('AUTOMATIC TRANSMISSION FLUID');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('BATTERY AND CABLES');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('BELTS');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('BRAKES');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('CABIN AIR FILTER');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('CHASSIS LUBRICATION');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('COOLANT ');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('DASHBOARD INDICATOR LIGHT ON');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('ENGINE AIR FILTER');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('ENGINE OIL');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('EXHAUST');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('HOSES');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('LIGHTS');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('POWER STEERING FLUID');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('STEERING AND SUSPENSION');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('TIRE INFLATION AND CONDITION');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('WHEEL ALIGNMENT');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('WINDSHIELD WASHER FLUID');
INSERT INTO ELDI.TYPE_SERVICES (SERVICE_NAME) VALUES ('WIPER BLADES');

-- DRIVER_QUALIFICATION
INSERT INTO ELDI.DRIVER_QUALIFICATION (QUALIFICATION_DESC) VALUES ('MOTORCYCLE, MOPED, TRIKE MOTORCYCLE');
INSERT INTO ELDI.DRIVER_QUALIFICATION (QUALIFICATION_DESC) VALUES ('WHEELCHAIR VEHICLE');
INSERT INTO ELDI.DRIVER_QUALIFICATION (QUALIFICATION_DESC) VALUES ('TRACTOR');
INSERT INTO ELDI.DRIVER_QUALIFICATION (QUALIFICATION_DESC) VALUES ('RIGID VEHICLES');
INSERT INTO ELDI.DRIVER_QUALIFICATION (QUALIFICATION_DESC) VALUES ('ANY');


)
INSERT INTO ELDI.DRIVERS VALUES ('D001' , 'JAIME PEREZ SUAREZ' , to_date('05/05/16','DD/MM/RR') , 3 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D002' , 'GILBERTO TORRES PONTEPIEDRA' , to_date('10/02/16','DD/MM/RR') , 1 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D003' , 'MARIO PALADINO QUIROZ' , to_date('06/01/17','DD/MM/RR') , 2 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D004' , 'PEDRO PABLO ALBA' , to_date('05/05/16','DD/MM/RR') , 4 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D005' , 'GILBERTO MARIN MOSQUERA' , to_date('10/02/16','DD/MM/RR') , 5 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D006' , 'CARLOS MARLON QUIROZ' , to_date('06/01/17','DD/MM/RR') , 1 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D007' , 'LUIS DIAZ SUAREZ' , to_date('05/05/16','DD/MM/RR') , 3 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D008' , 'MARINA VANEGAS ' , to_date('10/02/16','DD/MM/RR') , 1 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D009' , 'GILDARDO DIAZ QUIROZ' , to_date('06/01/17','DD/MM/RR') , 2 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D010' , 'MAGDA DIEZ' , to_date('08/01/17','DD/MM/RR') , 1 , 'INACTIVE' , to_date('28/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D011' , 'DENNIS GARRO' , to_date('05/05/16','DD/MM/RR') , 3 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D012' , 'CRISTIAN GUTIERREZ' , to_date('10/02/16','DD/MM/RR') , 1 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D013' , 'EDIL VANEGAS' , to_date('06/01/17','DD/MM/RR') , 2 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D014' , 'CATALINA GAVIRIA' , to_date('05/05/16','DD/MM/RR') , 4 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D015' , 'EMILIANA GARRO' , to_date('10/02/16','DD/MM/RR') , 5 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D016' , 'MATEO GARRO' , to_date('06/01/17','DD/MM/RR') , 1 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D017' , 'ANDRES FELIPE GARRO' , to_date('05/05/16','DD/MM/RR') , 3 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D018' , 'MARIA VANEGAS ' , to_date('10/02/16','DD/MM/RR') , 1 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D019' , 'GILDARDO ORREGO' , to_date('06/01/17','DD/MM/RR') , 2 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D020' , 'MAGDA MENDEZ' , to_date('08/01/17','DD/MM/RR') , 1 , 'INACTIVE' , to_date('28/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D021' , 'JAIME GIL' , to_date('05/05/16','DD/MM/RR') , 3 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D022' , 'GILBERTO SANTARROSA' , to_date('10/02/16','DD/MM/RR') , 1 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D023' , 'MARIO BROSS' , to_date('06/01/17','DD/MM/RR') , 2 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D024' , 'PEDRO LEON JARAMILLO' , to_date('05/05/16','DD/MM/RR') , 4 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D025' , 'ELGILBERTO GOMEZ' , to_date('10/02/16','DD/MM/RR') , 5 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D026' , 'CARLOS MUÑOZ' , to_date('06/01/17','DD/MM/RR') , 1 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D027' , 'LUIS EDUARDO GOMEZ' , to_date('05/05/16','DD/MM/RR') , 3 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D028' , 'JOHAN GAVIRIA  ' , to_date('10/02/16','DD/MM/RR') , 1 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D029' , 'NORELLY GAVIRIA' , to_date('06/01/17','DD/MM/RR') , 2 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D030' , 'HUMBERTO DIEZ' , to_date('08/01/17','DD/MM/RR') , 1 , 'INACTIVE' , to_date('28/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D031' , 'HUMBERTO GARRO' , to_date('05/05/16','DD/MM/RR') , 3 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D032' , 'JHON EDISON GARRO' , to_date('10/02/16','DD/MM/RR') , 1 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D033' , 'LUIGUI BROSS' , to_date('06/01/17','DD/MM/RR') , 2 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D034' , 'PEDRO PABLO MIJO' , to_date('05/05/16','DD/MM/RR') , 4 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D035' , 'JAMES GARRO' , to_date('10/02/16','DD/MM/RR') , 5 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D036' , 'DARIO GARRO' , to_date('06/01/17','DD/MM/RR') , 1 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D037' , 'LUIS GARRO' , to_date('05/05/16','DD/MM/RR') , 3 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D038' , 'JORGE MARIO CORREA' , to_date('10/02/16','DD/MM/RR') , 1 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D039' , 'MANUEL DIAZ' , to_date('06/01/17','DD/MM/RR') , 2 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D040' , 'MAGDALENA CORREA' , to_date('08/01/17','DD/MM/RR') , 1 , 'INACTIVE' , to_date('28/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D041' , 'BRUNO VALENTE' , to_date('08/01/17','DD/MM/RR') , 1 , 'INACTIVE' , to_date('28/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D042' , 'ROGOBERTO URAN ' , to_date('05/05/16','DD/MM/RR') , 3 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D043' , 'MARI HERNANDEZ' , to_date('10/02/16','DD/MM/RR') , 1 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D044' , 'HOGUITO BROSS' , to_date('06/01/17','DD/MM/RR') , 2 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D045' , 'ALEJANDRO ALZATE' , to_date('05/05/16','DD/MM/RR') , 4 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D046' , 'MONICA MARIA PIEDRAHITA' , to_date('10/02/16','DD/MM/RR') , 5 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D047' , 'ANA MILENA BLANDON ' , to_date('06/01/17','DD/MM/RR') , 1 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D048' , 'ALEJANDRA BLANDON' , to_date('05/05/16','DD/MM/RR') , 3 , 'ACTIVE' , to_date('12/01/17','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D049' , 'FABIO FRANCISCO GOMEZ' , to_date('10/02/16','DD/MM/RR') , 1 , 'ACTIVE' , to_date('21/04/16','DD/MM/RR'));
INSERT INTO ELDI.DRIVERS VALUES ('D050' , 'MANUEL MARULANDA' , to_date('06/01/17','DD/MM/RR') , 2 , 'INACTIVE' , to_date('18/01/17','DD/MM/RR'));



-- TYPE_OF_VEHICLES 
INSERT INTO ELDI.TYPE_OF_VEHICLES (TYPE_DESCRIPTION,QUALIFICATION_ID) VALUES ('CAR','N');
INSERT INTO ELDI.TYPE_OF_VEHICLES (TYPE_DESCRIPTION,QUALIFICATION_ID) VALUES ('HEAVY RIGID VEHICLE','S');
INSERT INTO ELDI.TYPE_OF_VEHICLES (TYPE_DESCRIPTION,QUALIFICATION_ID) VALUES ('LIGHT RIGID HEAVY VEHICLE','S');
INSERT INTO ELDI.TYPE_OF_VEHICLES (TYPE_DESCRIPTION,QUALIFICATION_ID) VALUES ('MEDIUM RIGID HEAVY VEHICLE','S');
INSERT INTO ELDI.TYPE_OF_VEHICLES (TYPE_DESCRIPTION,QUALIFICATION_ID) VALUES ('MOPED','S');
INSERT INTO ELDI.TYPE_OF_VEHICLES (TYPE_DESCRIPTION,QUALIFICATION_ID) VALUES ('MOTORCYCLE','S');
INSERT INTO ELDI.TYPE_OF_VEHICLES (TYPE_DESCRIPTION,QUALIFICATION_ID) VALUES ('TRACTOR','S');
INSERT INTO ELDI.TYPE_OF_VEHICLES (TYPE_DESCRIPTION,QUALIFICATION_ID) VALUES ('TRIKE MOTORCYCLE','S');
INSERT INTO ELDI.TYPE_OF_VEHICLES (TYPE_DESCRIPTION,QUALIFICATION_ID) VALUES ('WHEELCHAIR VEHICLE','S');


-- VEHICLES 

INSERT INTO ELDI.VEHICLES VALUES ('FKV56D','REPAIRING','1300','2016',1,to_date('20/05/16','DD/MM/RR'),5004300,4990000,123400,to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('GTR567','ACTIVE','500','2017',6,to_date('10/01/17','DD/MM/RR'),456000000,420000000,320000,to_date('01/02/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('WDR689','ACTIVE','34000','2013',9,to_date('07/03/13','DD/MM/RR'),567000900,456790000,2800000,to_date('05/05/14','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV16D' , 'REPAIRING' , 1300 , 2016 , 1 , to_date('20/05/16','DD/MM/RR') , 5004300 , 4990000 , 123400 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV17D' , 'REPAIRING' , 1400 , 2001 , 2 , to_date('20/05/01','DD/MM/RR') , 5004400 , 4991000 , 123500 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV18D' , 'REPAIRING' , 1500 , 2002 , 3 , to_date('20/05/02','DD/MM/RR') , 5004500 , 4992000 , 123600 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV19D' , 'REPAIRING' , 1600 , 2003 , 4 , to_date('20/05/03','DD/MM/RR') , 5004600 , 4993000 , 123700 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV71D' , 'REPAIRING' , 1700 , 2004 , 5 , to_date('20/05/04','DD/MM/RR') , 5004700 , 4994000 , 123800 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV20D' , 'REPAIRING' , 1800 , 2005 , 6 , to_date('20/05/05','DD/MM/RR') , 5004800 , 4995000 , 123900 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV21D' , 'REPAIRING' , 1900 , 2006 , 7 , to_date('20/05/06','DD/MM/RR') , 5004900 , 4996000 , 124000 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV22D' , 'REPAIRING' , 2000 , 2007 , 8 , to_date('20/05/07','DD/MM/RR') , 5005000 , 4997000 , 124100 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV23D' , 'REPAIRING' , 2100 , 2008 , 9 , to_date('20/05/08','DD/MM/RR') , 5005100 , 4998000 , 124200 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV24D' , 'REPAIRING' , 2200 , 2009 , 1 , to_date('20/05/09','DD/MM/RR') , 5005200 , 4999000 , 124300 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV25D' , 'REPAIRING' , 2300 , 2010 , 2 , to_date('20/05/10','DD/MM/RR') , 5005300 , 5000000 , 124400 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV26D' , 'REPAIRING' , 2400 , 2011 , 3 , to_date('20/05/11','DD/MM/RR') , 5005400 , 5001000 , 124500 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV27D' , 'REPAIRING' , 2500 , 2012 , 4 , to_date('20/05/12','DD/MM/RR') , 5005500 , 5002000 , 124600 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV28D' , 'REPAIRING' , 2600 , 2013 , 5 , to_date('20/05/13','DD/MM/RR') , 5005600 , 5003000 , 124700 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV29D' , 'ACTIVE' , 2700 , 2014 , 6 , to_date('20/05/14','DD/MM/RR') , 5005700 , 5004000 , 124800 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV30D' , 'ACTIVE' , 2800 , 2015 , 7 , to_date('20/05/15','DD/MM/RR') , 5005800 , 5005000 , 124900 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV31D' , 'ACTIVE' , 2900 , 2016 , 8 , to_date('20/05/16','DD/MM/RR') , 5005900 , 5006000 , 125000 , to_date('13/01/17','DD/MM/RR'));
INSERT INTO ELDI.VEHICLES VALUES ('FKV32D' , 'ACTIVE' , 3000 , 2017 , 9 , to_date('20/05/17','DD/MM/RR') , 5006000 , 5004000 , 125100 , to_date('13/01/17','DD/MM/RR'));


-- VEH_DRIVER_AUTHO (ES UNO POR CADA CONDUCTOR - ENTIDAD DEBIL FALTAN 40)

INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (8,2, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (17,6, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (2,8, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (9,10, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (18,12, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (11,16, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (20,18, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (8,20, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (17,22, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (2,26, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (9,28, 'N' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (18,30, 'N' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (11,32, 'N' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (20,36, 'N' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (8,38, 'N' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (17,40, 'N' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (2,41, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (9,43, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (18,47, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (11,49, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (3,3, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (12,9, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (21,13, 'N' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (3,19, 'N' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (12,23, 'N' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (21,29, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (3,33, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (12,39, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (21,44, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (21,50, 'N' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (10,1, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (19,7, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (10,11, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (19,17, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (10,21, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (19,27, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (10,31, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (19,37, 'N' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (10,42, 'N' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (19,48, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (5,4, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (14,14, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (6,24, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (15,34, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (7,45, 'N' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (1,5, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (4,15, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (13,25, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (1,35, 'S' ,to_date('20/05/17','DD/MM//RR'));
INSERT INTO ELDI.VEH_DRIVER_AUTHO VALUES (4,46, 'S' ,to_date('20/05/17','DD/MM//RR'));



-- INSURANCE CLAIMS (FALTAN 8 )
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (1 , 'sd-40567' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (4 , 'sd-40568' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (13 , 'sd-40569' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (5 , 'sd-40570' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (14 , 'sd-40571' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (6 , 'sd-40572' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (15 , 'sd-40573' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (7 , 'sd-40574' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (16 , 'sd-40575' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (8 , 'sd-40576' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (17 , 'sd-40577' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (9 , 'sd-40578' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (10 , 'sd-40579' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (11 , 'sd-40580' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');
INSERT INTO ELDI.INSURANCE_CLAIMS VALUES (12 , 'sd-40581' , to_date('07/04/17','DD/MM/RR') , to_date('20/04/17','DD/MM/RR') , 'Choque');


-- SERVICES

INSERT INTO ELDI.SERVICE (REG_ID,ISSUE_DATE) VALUES ('8',to_date('18/05/17','DD/MM/RR'));
INSERT INTO ELDI.SERVICE (REG_ID,ISSUE_DATE) VALUES ('5',to_date('16/05/17','DD/MM/RR'));
INSERT INTO ELDI.SERVICE (REG_ID,ISSUE_DATE) VALUES ('4',to_date('10/05/17','DD/MM/RR'));
INSERT INTO ELDI.SERVICE (REG_ID,ISSUE_DATE) VALUES ('8',to_date('11/05/17','DD/MM/RR'));
INSERT INTO ELDI.SERVICE (REG_ID,ISSUE_DATE) VALUES ('5',to_date('21/05/17','DD/MM/RR'));

-- SERVICE_DETAIL
INSERT INTO ELDI.SERVICES_DETAIL (SERVICE_TYPE_ID,DESCRIPTION,SERVICE_STATUS,SERVICE_ID) VALUES ('4','Mantemimiento','OK','1');
INSERT INTO ELDI.SERVICES_DETAIL (SERVICE_TYPE_ID,DESCRIPTION,SERVICE_STATUS,SERVICE_ID) VALUES ('5','Daño','PENDING','2');
INSERT INTO ELDI.SERVICES_DETAIL (SERVICE_TYPE_ID,DESCRIPTION,SERVICE_STATUS,SERVICE_ID) VALUES ('6','A demanda','OK','3');
INSERT INTO ELDI.SERVICES_DETAIL (SERVICE_TYPE_ID,DESCRIPTION,SERVICE_STATUS,SERVICE_ID) VALUES ('7','Mantenimiento','OK','4');
INSERT INTO ELDI.SERVICES_DETAIL (SERVICE_TYPE_ID,DESCRIPTION,SERVICE_STATUS,SERVICE_ID) VALUES ('8','Daño','PENDING','5');











